[package]
name = "ofx-text"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
unicode-properties.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
