[package]
name = "ofx-upgrade"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
flate2.workspace = true
ofx-text.workspace = true
reqwest.workspace = true
semver.workspace = true
sha2.workspace = true
tar.workspace = true
tempfile.workspace = true
thiserror.workspace = true

[dev-dependencies]
ofx-http.workspace = true
tokio = { workspace = true, features = ["macros"] }

[lints]
workspace = true
