[package]
name = "ofx-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
getrandom.workspace = true
ofx-contract.workspace = true
ofx-text.workspace = true
percent-encoding.workspace = true
rustix = { workspace = true, features = ["fs"] }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
